### ISSUE TITLE
Typo: Miami Case Study

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/baldwin#4]
First paragraph has a misspelled word. Could you please replace that paragraph with the paragraph below.

During the move in weekend, Miami University wanted to take advantage of an engaged audience in an effort to help "move" Miami forward. Their alumni team began developing the "Move in Miami" campaign and needing a website to help engage and collect donors. Baldwin Creative & Co. was brought in on a condensed timeframe to make it happen.

**Comment by Toddses** [comment]
@jonathanhauge Going to leave this up to you guys when we hit the content integration phase.
